# Netlify Configuration File

[build]
  # Directory to change to before starting build
  base = "/"
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the built files
  publish = "build"
  
  # Node version for builds
  environment = { NODE_VERSION = "20", GENERATE_SOURCEMAP = "false", CI = "false" }

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy (if needed in the future)
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-api-domain.com/api/:splat"
#   status = 200
#   force = true

# Environment-specific configurations
[context.production]
  environment = { REACT_APP_ENABLE_ANALYTICS = "true" }

[context.deploy-preview]
  environment = { REACT_APP_ENABLE_ANALYTICS = "false" }

[context.branch-deploy]
  environment = { REACT_APP_ENABLE_ANALYTICS = "false" }